name: fungiscan
description: A Flutter-based mushroom identification app with AI recognition, offline functionality, and location tracking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  
  # Networking & Storage
  http: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  
  # Image Processing & Camera
  image: ^4.1.3
  camera: ^0.10.5+4
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  
  # Location & Mapping
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.0.0
  
  # Permissions
  permission_handler: ^11.0.0
  
  # ML & Identification
  google_mlkit_pose_detection: ^0.10.0
  google_mlkit_smart_reply: ^0.10.0
  google_mlkit_entity_extraction: ^0.11.0
  google_mlkit_commons: ^0.6.0
  tflite_flutter: ^0.10.3
  
  # Authentication & Backend
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.6
  
  # Security & Encryption
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sembast: ^3.5.0+1
  flutter_secure_storage: ^9.0.0
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_markdown: ^0.6.17
  lottie: ^2.6.0
  
  # Utilities
  uuid: ^4.0.0
  intl: ^0.18.1
  connectivity_plus: ^5.0.1
  local_auth: ^2.1.7
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  
  # Social & Community
  webview_flutter: ^4.2.4
  socket_io_client: ^2.0.3+1
  
  # Monetization
  purchases_flutter: ^6.0.0
  in_app_purchase: ^3.1.11
  
  # App Configuration
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  flutter_local_notifications: ^16.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  
  # Testing
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/ml/
    - assets/data/
    - .env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700