name: fungiscan
description: A Flutter-based mushroom identification app with AI recognition, offline functionality, and location tracking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  image: ^4.1.3
  camera: ^0.10.5+4
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.0
  # Temporarily commenting out tflite_flutter for web compatibility
  # tflite_flutter: ^0.10.3
  uuid: ^4.0.0
  intl: ^0.18.1
  provider: ^6.0.5
  connectivity_plus: ^5.0.1
  local_auth: ^2.1.7
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.2
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  flutter_local_notifications: ^16.1.0
  # Temporarily commented out Firebase dependencies for web development
  # firebase_core: ^2.15.1
  # firebase_auth: ^4.9.0
  # cloud_firestore: ^4.9.1
  # firebase_storage: ^11.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/ml/
    - assets/data/
    - .env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700